#**SVD**

#import libraries

In [4]:
import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OrdinalEncoder
%matplotlib inline

#Load the tabular dataset :

dataset :


    [1, 2, 1, 0, 4],

    [2, 3, 4, 0, 2],

    [3, 1, 1, 0, 5],

    [4, 0, 2, 5, 0],

    [5, 4, 0, 1, 2]


In [32]:
df = pd.DataFrame(np.array([
    [5, 2, 1, 0, 4],

[7, 3, 4, 2, 2],

[3, 1, 1, 8, 5],

[4, 9, 2, 5, 1],

[5, 2, 3, 1, 2]
    
]))

#Perform Singular Value Decomposition (SVD)


# Extract the singular values and vectors

In [42]:
U, s, VT = np.linalg.svd(df)
VT

array([[-0.60226822, -0.4878509 , -0.28379522, -0.45356135, -0.33617981],
       [-0.45737139, -0.16763871, -0.27505977,  0.80058875,  0.21472878],
       [ 0.34881991, -0.7768483 ,  0.09717371, -0.06700177,  0.51078315],
       [-0.0673734 ,  0.33274247, -0.61325992, -0.34668403,  0.62327019],
       [ 0.54942688, -0.14031366, -0.67695785,  0.16929472, -0.43761803]])

In [64]:
singular_values = np.diag(s)
left_singular_vectors = U
right_singular_vectors = VT.T

In [85]:
VT.T

array([[-0.60226822, -0.45737139,  0.34881991, -0.0673734 ,  0.54942688],
       [-0.4878509 , -0.16763871, -0.7768483 ,  0.33274247, -0.14031366],
       [-0.28379522, -0.27505977,  0.09717371, -0.61325992, -0.67695785],
       [-0.45356135,  0.80058875, -0.06700177, -0.34668403,  0.16929472],
       [-0.33617981,  0.21472878,  0.51078315,  0.62327019, -0.43761803]])

# Perform dimensionality reduction by selecting top k singular values and vectors


In [74]:
k = 3
reduced_dataset = np.dot(np.dot(left_singular_vectors[:, :k], singular_values[:k, :k]), right_singular_vectors[:,:k].T)

# Print the original and reduced datasets


In [95]:
#Original
np.array(df)

array([[5, 2, 1, 0, 4],
       [7, 3, 4, 2, 2],
       [3, 1, 1, 8, 5],
       [4, 9, 2, 5, 1],
       [5, 2, 3, 1, 2]])

In [87]:
#reduced
reduced_dataset

array([[5.12732002, 1.27064167, 2.38080054, 0.7590149 , 2.6406468 ],
       [6.80826968, 3.48227617, 3.28007623, 1.49334546, 2.93492844],
       [2.99208018, 1.04612163, 0.91244793, 7.95200884, 5.08591584],
       [4.03176655, 8.8692955 , 2.23137465, 5.13641595, 0.75339477],
       [5.10732865, 2.16547942, 2.44212386, 0.83383184, 2.2627169 ]])

#**Well done :)**